---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: rashmi-hpa-demo-deployment
spec:
 selector:
   matchLabels:
     run: rashmi-hpa-demo-deployment
 replicas: 1
 template:
   metadata:
     labels:
       run: rashmi-hpa-demo-deployment
   spec:
     containers:
     - name: rashmi-hpa-demo-deployment
       image: k8s.gcr.io/hpa-example
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m
...
